baseURL: "https://api.example.com"
languageCode: "en-us"
title: "Documentation"
theme: "hexon-hugo-theme"

markup:
  highlight:
    style: "dracula"
  goldmark:
    renderer:
      unsafe: true

params:
  companyName: ExampleCompany
  companyId: example_company
  appUrl: https://wallet.example.com
  invoicesApi: https://api.invoices.example.com
  businessApi: https://api.business.example.com

  logoUrl: https://example.com
  logoImage: /images/logo.svg
  heroImage: /images/hero.svg
  favicon: /images/favicon.png

  primaryColor: "#5336FF"
  secondaryColor: "#A4A5F5"

  extraNavItems:
    - title: Sign in
      url: https://wallet.example.com

  extraFooterItems:
    - title: Sign in
      url: https://wallet.example.com
